export const GET_FLIGHTS = 'GET_FLIGHTS';
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS';
export const GET_FLIGHTS_FAILED = 'GET_FLIGHTS_FAILED';
export const GET_FLIGHTS_REQUESTED = 'GET_FLIGHTS_REQUESTED';